export {default as AboutView} from './AboutView'
export {default as ContactView} from './ContactView'
export {default as HomeView} from './HomeView'
export {default as NotFoundView} from './NotFoundView'
export {default as TeamView} from './TeamView'
export {default as FaqView} from './FaqView'
